server_region = "us-east-2"
region_shortname = "use2"
env = "prod"
server_image_id = "ami-0af13f091353ff69d"
ssh_security_group = ""
use_spot_instance = true
ark_map_names = [ "TheIsland" ]
minecraft_map_names = []
valheim_map_names = []