{{ $providerName := print "aws-secrets-" .Values.env "-" .Values.game }}
{{ $providerName := lower $providerName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $providerName }}
spec:
  provider: aws
  parameters:
    objects: |
    {{- range $secret := .Values.secrets }}
      - objectName: {{ $secret }}
        objectType: "secretsmanager"
    {{- end }}