{{ $serviceAccountName := print "jks-gameservers-" .Values.env "-" .Values.game "-serviceaccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  labels:
    game: {{ .Values.game }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRoleArn }}
    eks.amazonaws.com/sts-regional-endpoints: "true"