{{ $deploymentName := print "Deployment-" .Values.env "-" .Values.game "-" .Values.map}}
{{ $deploymentName := lower $deploymentName }}
{{ $initImage := print "jkstenzel95/jks_gameserver_init:" .Values.imageTag}}
{{ $image := print "jkstenzel95/jks_gameserver_runtime:" .Values.imageTag}}
{{ $serviceAccountName := print "jks-gameservers-" .Values.env "-" .Values.game "-serviceaccount" | lower }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    cluster: "jks"
    game: {{ .Values.game }}
    map: {{ .Values.map }}
    mapSet: {{ .Values.mapSet }}
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster: "jks"
      game: {{ .Values.game }}
      map: {{ .Values.map }}
      mapSet: {{ .Values.mapSet }}
  template:
    metadata:
      annotations: # ?
      labels:
        cluster: "jks"
        game: {{ .Values.game }}
        map: {{ .Values.map }}
        mapSet: {{ .Values.mapSet }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      nodeSelector:
        game: {{ .Values.game }}
        mapSet: {{ .Values.mapSet }}
      volumes:
      - name: jks-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets"
      - name: game-servers
        hostPath:
          path: /mnt/gameservers
          type: Directory
      - name: scripts-dir
        hostPath:
          path: /gameservers-package/shared/scripts/runtime
          type: Directory
      - name: game-data
        hostPath:
          path: /gameservers-package/shared/data
          type: Directory
      containers:
      - name: gameserver
        image: {{ $image }}
        resources:
          requests:
            memory: "4Gi"
          limits:
            memory: "6Gi"
        volumeMounts:
        - mountPath: /gameservers
          name: game-servers
        - mountPath: /scripts
          name: scripts-dir
        - mountPath: /game-data
          name: game-data
        - name: jks-secrets
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: SERVER_MOUNT_LOCATION
          value: "/gameservers"
        - name: GAME_NAME
          value: {{ .Values.game }}
        - name: MAP_NAME
          value: {{ .Values.map }}
        - name: ENVIRONMENT
          value: {{ .Values.env }}
        - name: REGION_SHORTNAME
          value: {{ .Values.regionShortname }}
{{ .Files.Get .Values.environmentVariableFile | indent 8}}
        {{- range $port := .Values.ports }}
        - name: {{ $port.name }}
          value: !!string {{ $port.number }}
        {{- end}}
        ports:
          {{- range $port := .Values.ports }}
          - containerPort: {{ $port.number }}
            name: {{ $port.name | replace "_" "-" | lower }}
          {{- end}}