{{ $deploymentName := print "Deployment-" .Values.game "-" .Values.map}}
{{ $initImage := print "jkstenzel95/jks_gameserver_init:" .Values.imageTag}}
{{ $image := print "jkstenzel95/jks_gameserver_runtime:" .Values.imageTag}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    game: {{ .Values.game }}
    map: {{ .Values.map }}
spec:
  replicas: 1
  selector:
    matchLabels:
      game: {{ .Values.game }}
      map: {{ .Values.map }}
  template:
    metadata:
      annotations: # ?
      labels:
        game: {{ .Values.game }}
        map: {{ .Values.map }}
    spec:
      # imagePullSecrets:    # Think about this later...
      tolerations:
      - key: "game"
        operator: "Equal"
        value: {{ .Values.game }}
        effect: "NoExecute"
      - key: "map"
        operator: "Equal"
        value: {{ .Values.map }}
        effect: "NoExecute"
      initContainers:
      - name: gameserver-init
        image: {{ $initImage }}
      containers:
      - name: gameserver
        image: {{ $image }}
        env:
        - name: SERVER_MOUNT_LOCATION
          value: "/mnt/gameservers"
        - name: GAME_NAME
          value: {{ .Values.game }}
        - name: MAP_NAME
          value: {{ .Values.map }}
        - name: ENVIRONMENT
          value: {{ .Values.env }}
        - name: REGION_SHORTNAME
          value: {{ .Values.regionShortname }}
        - name: BACKUP_STORAGE_NAME
          value: {{ .Values.backupStorageName }}
        - name: RESOURCE_BUCKET_NAME
          value: { .Values.resourceBucketName }
{{ .Files.Get .Values.environmentVariableFile | indent 8 }}
        ports:
          {{- range $port := .Values.ports }}
          - containerPort: {{ $port.number }}
            name: {{ $port.name }}
          {{- end}}