{{ if .Values.requestVolume }}
{{ $deploymentName := print "Deployment-" .Values.env "-" .Values.game "-" .Values.map }}
{{ $deploymentName := lower $deploymentName }}
{{ $volumeName := print $deploymentName "-volume" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $volumeName }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $volumeName }}
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-retain
  volumeMode: Filesystem
  claimRef:
     namespace: default
     name: {{ $volumeName }}
  awsElasticBlockStore:
    volumeID: {{ .Values.volumeId }}
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $volumeName }}
spec:
  storageClassName: gp2-retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{ end }}