{{ $serviceName := print "Service-" .Values.game "-" .Values.map}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    game: {{ .Values.game }}
    map: {{ .Values.map }}
spec:
  type: NodePort
  ports:
    {{- range $port := .Values.ports }}
    - port: {{ $port.number }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    game: {{ .Values.game }}
    map: {{ .Values.map }}