game: Minecraft
env: dev
region: us-east-2
regionShortname: use2
mapSet: main
needsSetup: "true"
requestsMemory: "2Gi"
limitsMemory: "4Gi"
requestVolume: true
flexibleDeployment: true
backupStorageName: "jks-gs-dev-use2-minecraft-backup-bucket"
resourceBucketName: "jks-gs-dev-use2-minecraft-gameresources-bucket"
storageSize: 56
volumeId: vol-0e1490f3e5766ecbb

hasSecrets: false